[build]
  command = "pushd packages/client; yarn build; popd"
  publish = "packages/client/dist"

[build.environment]
  APP_URL = "https://tourname.netlify.com"
  AUTH_CLIENT_ID = "ZpxENtfYcVeKgokEz5WkNpyy8PQC8XmN"
  AUTH_CALLBACK_URL = "https://tourname.netlify.com/auth/callback"
  API_URL = "https://tourname-staging.now.sh/graphql"

# COMMENT: This a rule for Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
