aliases:
  - &working_directory ~/tourname

  - &restore_yarn_cache
    keys:
      - v3-yarn-cache-{{ checksum "yarn.lock" }}
      - v3-yarn-cache

  - &save_yarn_cache
    key: v3-yarn-cache-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn
      - node_modules

version: 2
jobs:
  lint_and_test:
    working_directory: *working_directory
    docker:
      - image: circleci/node:8@sha256:44c6136b6b55003fa12321aa1eb790a5a6482edb461227cb56daf488178d04dc
    steps:
      - checkout
      - restore_cache: *restore_yarn_cache
      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile
      - save_cache: *save_yarn_cache
      - run:
          name: Run linters
          command: yarn lint

workflows:
  version: 2
  # Workflow for master branch pipeline
  build_and_deploy:
    jobs:
      - lint_and_test
