aliases:
  - &working_directory ~/tourname

  - &restore_yarn_cache
    keys:
      - v2-yarn-cache-{{ checksum "yarn.lock" }}
      - v2-yarn-cache

  - &save_yarn_cache
    key: v2-yarn-cache-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn
      - node_modules

version: 2
jobs:
  lint_and_test:
    working_directory: *working_directory
    docker:
      - image: circleci/node:8@sha256:0ac63bc3d5a224deac83654a322a995332809c9f535434dfd195c26e7310ec3e
    steps:
      - checkout
      - restore_cache: *restore_yarn_cache
      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile
      - save_cache: *save_yarn_cache
      - run:
          name: Run linters
          command: yarn lint

workflows:
  version: 2
  # Workflow for master branch pipeline
  build_and_deploy:
    jobs:
      - lint_and_test
