aliases:
  - &working_directory ~/tourname

  - &restore_yarn_cache
    keys:
      - v1-yarn-cache-{{ checksum "yarn.lock" }}
      - v1-yarn-cache

  - &save_yarn_cache
    key: v1-yarn-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules

version: 2
jobs:
  lint_and_test:
    working_directory: *working_directory
    docker:
      - image: circleci/node:8@sha256:a971d3cc8dd7e5166851445e9a15abcf1115cc042db44c5768dfac2d4d44f92e
    steps:
      - checkout
      - restore_cache: *restore_yarn_cache
      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile
      - save_cache: *save_yarn_cache
      - run:
          name: Run linters
          command: yarn lint

workflows:
  version: 2
  # Workflow for master branch pipeline
  build_and_deploy:
    jobs:
      - lint_and_test
