aliases:
  - &working_directory ~/tourname

  - &restore_yarn_cache
    keys:
      - v1-yarn-cache-{{ checksum "yarn.lock" }}
      - v1-yarn-cache

  - &save_yarn_cache
    key: v1-yarn-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules

version: 2
jobs:
  lint_and_test:
    working_directory: *working_directory
    docker:
      # specify the version you desire here
      - image: circleci/node:8
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache: *restore_yarn_cache
      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile
      - save_cache: *save_yarn_cache
      - run:
          name: Run linters
          command: yarn lint
      - persist_to_workspace:
          root: ~/
          paths:
            # Include the entire project folder
            - tourname
  build:
    - attach_workspace:
        at: *working_directory
    - run:
        name: Building production bundles
        command: yarn build

workflows:
  version: 2
  # Workflow for master branch pipeline
  build_and_deploy:
    jobs:
      - lint_and_test
