// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Downshift         from "downshift";
import * as Js_boolean        from "bs-platform/lib/es6/js_boolean.js";
import * as ReasonReact       from "reason-react/src/ReasonReact.js";
import * as Js_null_undefined from "bs-platform/lib/es6/js_null_undefined.js";

function optionToBool(optional) {
  if (optional) {
    return /* true */1;
  } else {
    return /* false */0;
  }
}

function make(defaultSelectedItem, defaultHighlightedIndex, defaultInputValue, defaultIsOpen, itemToString, selectedItemChanged, getA11yStatusMessage, onChange, onSelect, onStateChange, onInputValueChange, itemCount, highlightedIndex, inputValue, isOpen, selectedItem, render, id, environment, onOuterClick, _) {
  return ReasonReact.wrapJsForReason(Downshift.default, {
              defaultSelectedItem: Js_null_undefined.from_opt(defaultSelectedItem),
              defaultHighlightedIndex: Js_null_undefined.from_opt(defaultHighlightedIndex),
              defaultInputValue: Js_null_undefined.from_opt(defaultInputValue),
              defaultIsOpen: Js_boolean.to_js_boolean(optionToBool(defaultIsOpen)),
              itemToString: Js_null_undefined.from_opt(itemToString),
              selectedItemChanged: Js_null_undefined.from_opt(selectedItemChanged),
              getA11yStatusMessage: Js_null_undefined.from_opt(getA11yStatusMessage),
              onChange: Js_null_undefined.from_opt(onChange),
              onSelect: Js_null_undefined.from_opt(onSelect),
              onStateChange: Js_null_undefined.from_opt(onStateChange),
              onInputValueChange: Js_null_undefined.from_opt(onInputValueChange),
              itemCount: Js_null_undefined.from_opt(itemCount),
              highlightedIndex: Js_null_undefined.from_opt(highlightedIndex),
              inputValue: Js_null_undefined.from_opt(inputValue),
              isOpen: Js_boolean.to_js_boolean(optionToBool(isOpen)),
              selectedItem: Js_null_undefined.from_opt(selectedItem),
              render: render,
              id: Js_null_undefined.from_opt(id),
              environment: Js_null_undefined.from_opt(environment),
              onOuterClick: Js_null_undefined.from_opt(onOuterClick)
            }, /* array */[]);
}

var Downshift$1 = /* module */[/* make */make];

export {
  optionToBool ,
  Downshift$1    as Downshift,
  
}
/* downshift Not a pure module */
