// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Downshift   from "downshift";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

function make(render, children) {
  return ReasonReact.wrapJsForReason(Downshift.default, {
              render: render
            }, children);
}

var Downshift$1 = /* module */[/* make */make];

export {
  Downshift$1 as Downshift,
  
}
/* downshift Not a pure module */
