version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.8@sha256:a0db4fa719944da226e78b8925ebff08a7790d3a323c386d0f89c98b3513d872
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            active: true
            host: db
            port: 3306
            user: root
            password: prisma
  db:
    image: mysql:5.7@sha256:81679f23e0ece3e50a7300050191272e5afbf5b66be9b60d2ee0e8b575b152e2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
